- hosts: all

  vars:
    ulimit_soft: 65535
    ulimit_hard: 65535
    docker_engine_version: 1.11*
    mesos_version: 0.28*
    marathon_version: 1.1*

  tasks:
    - name: Add docker repo key
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
        state: present

    - name: Add docker repo
      apt_repository:
        repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
        state: present

    - name: Add mesossphere apt key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: E56151BF

    - name: Add mesosphere repo
      apt_repository:
        repo: "deb http://repos.mesosphere.com/ubuntu trusty main"
        state: present

    - name: Add openjdk repo
      apt_repository:
        repo: "ppa:openjdk-r/ppa"
        state: present

    - name: Install basic packages
      apt: 
        name: "{{item}}"
        state: installed
        force: yes
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - linux-image-extra-{{ ansible_kernel }}
        - build-essential
        - vim
        - unzip
        - python-setuptools
        - python-dev
        - gcc
        - make
        - ntp
        - btrfs-tools
        - aufs-tools
        - openjdk-8-jdk
        - docker-engine={{docker_engine_version}}
        - mesos={{mesos_version}}
        - marathon={{marathon_version}}
        - libffi-dev
        - libssl-dev

    - name: stop docker service
      service:
        name: docker
        state: stopped

    - name: remove device mapper
      file:
        path: /var/lib/docker/devicemapper
        state: absent

    - easy_install: name=pip state=present

    - name: install pip packages
      pip: name={{item}}
      with_items:
        - python-apt
        - boto
        - boto3
        - virtualenv
        - ipython
        - supervisor
        - ansible
        - pandas

    - name: Disable services
      service:
        name: "{{item}}"
        enabled: no
      with_items:
      - zookeeper
      - mesos-master
      - mesos-slave
      - marathon
      - docker

    - name: Allow vagrant to use docker without sudo
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: set ulimits
      template: src=limits.conf.j2 dest=/etc/security/limits.conf

    - name: save build info
      blockinfile:
        dest: /opt/box_info
        create: yes
        block: |
          build_time: {{ansible_date_time.iso8601}}
          docker_engine_version: {{docker_engine_version}}
          mesos_version: {{mesos_version}}
          marathon_version: {{marathon_version}}

    - name: white wipe disk
      shell: bash /vagrant/playbooks/box_builder/files/cleanup.sh

